parameters:
  orkestra.pdf.tcpdf_factory.class:   Orkestra\Bundle\PdfBundle\Factory\TcPdfFactory
  orkestra.pdf.wkpdf_factory.class:   Orkestra\Bundle\PdfBundle\Factory\WkPdfFactory
  orkestra.pdf.zendpdf_factory.class: Orkestra\Bundle\PdfBundle\Factory\ZendPdfFactory
  orkestra.pdf.pdf_helper.class:      Orkestra\Bundle\PdfBundle\Helper\PdfHelper

services:
  # Factories
  orkestra.pdf.tcpdf_factory:
    class: %orkestra.pdf.tcpdf_factory.class%
  orkestra.pdf.wkpdf_factory:
    class: %orkestra.pdf.wkpdf_factory.class%
  orkestra.pdf.zendpdf_factory:
    class: %orkestra.pdf.zendpdf_factory.class%

  # Helpers
  orkestra.pdf.pdf_helper:
    class: %orkestra.pdf.pdf_helper.class%
    arguments: [ @orkestra.pdf.pdf_factory, @templating ]

  # Utility services
  orkestra.pdf.cache_warmer:
    public: false
    class: Orkestra\Bundle\PdfBundle\CacheWarmer\PdfCacheWarmer
    arguments: [ @service_container ]
    tags:
      - { name: kernel.cache_warmer }

  # Abstract generator
  orkestra.pdf.abstract_generator:
    public: false
    abstract: true
    class: Orkestra\Bundle\PdfBundle\Generator\AbstractPdfGenerator
    arguments: [ @orkestra.pdf.pdf_factory, @templating ]
